# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read          # Vereist voor actions/checkout
      security-events: write  # Vereist om CodeQL-resultaten te uploaden naar de Security tab
      actions: read           # Vereist voor github/codeql-action/init

    steps:
      - uses: actions/checkout@v4

      - name: Initialiseer CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Voer CodeQL-analyse uit
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:python" # Helpt bij het correct categoriseren van resultaten

      #- name: Run tests
        #run: |
          #source venv/bin/activate
          #pytest --disable-warnings -q

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Predictive-Monitoring-Tool'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BC35D8BAB49943A5BD36D3461A9D2CFF }}
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}




